### PR TITLE
Support Laravel 8

### PR DESCRIPTION
**Pull request by abderrazzak-oxa**

### CODE REVIEW

**Comment by sashsvamir** [comment]
ErrorException
Undefined property: anlutro\LaravelSettings\SettingsManager::$app (View: /Users/aleyrsrglts/Sites/baydar-valley.com/project-laravel/resources/views/layouts/app.blade.php)

**Comment by abderrazzak-oxa** [comment]
@sashsvamir, @anlutro 
Now this package will support <= laravel 8 without any problem

**Comment by bweston92** [comment]
Thanks for the PR.

**Comment by bweston92** [comment]
This has now been released as v1.0.0.

**Pull request merged**
