### PR TITLE
Added Total Downloads badge

### PR DESCRIPTION
**Pull request by proshanto**

### CODE REVIEW

**Comment by anlutro** [comment]
Honest question - is this something people actually care about?

**Comment by proshanto** [comment]
Honest answer - when i'm confused about choosing a package between various packages which solves almost similar problem and i have no idea about them, then i almost go with the most popular package.

**Comment by anlutro** [comment]
Hmm, that makes sense when you're on packagist and comparing packages, but when viewing the github page of a package it might make less sense. I guess if the download counter is notably high (I don't know what counts as notable these days, 50K?) that's potentially a good sign.

**Comment by anlutro** [comment]
I thought about whether I wanted to add this to all my packages, and decided some time ago, but forgot about this issue.

I don't really want people to consider how many downloads I have when downloading my packages. I never do a good job advertising them anyway. If anything, I'd like people to focus on the quality of the readme file or the code - a download counter might take some focus away from that.

Regardless, thanks for bringing it up - it wasn't something I'd really thought about previously.

**Pull request closed without merging**
