### PR TITLE
Create Migration script

### PR DESCRIPTION
**Pull request by matriphe**
Create migration script for usage of database storage. I updated the README.md too.

### CODE REVIEW

**Comment by anlutro** [comment]
Why not. Thanks!

**Comment by rephole** [comment]
Please release a new version. Because there is migration command in readme, but v0.4.0 is not including migrations directory.

**Comment by anlutro** [comment]
Will do, package migrations aren't very important in my mind so I kinda forgot about it.

**Comment by matriphe** [comment]
@rephole have you tried to change the composer require to 0.4.1? if you use the ~0.4 it should automatically update to the latest (0.4.1) version.

just check the `composer.json` and change to this: `"anlutro/l4-settings": "~0.4"` and pull using `composer update`

**Comment by anlutro** [comment]
I only released 0.4.1 today, after making that comment :)

**Comment by matriphe** [comment]
@anlutro ah, nice! :dancers:

**Pull request merged**
