### PR TITLE
Adding support for Laravel 10.

### LINKED ISSUE #172: Support Laravel 10

### PR DESCRIPTION
**Pull request by aglipanci**
fixes #172

### CODE REVIEW

**Comment by aglipanci** [comment]
@anlutro I would really appreciate if you can merge and tag a release for Laravel 10 support.

**Comment by bweston92** [comment]
Hi @aglipanci 

Whilst I haven't got time to thoroughly check this works I also cannot see any changes which would affect it.

**Comment by aglipanci** [comment]
Thanks @bweston92! This version of Laravel doesn't seem to introduce any major breaking change so it should work fine. The tests also passed.

**Comment by bweston92** [comment]
Hi @aglipanci should be in v1.3.0 :) thanks for your contribution

**Pull request merged**
