### PR TITLE
Update only changed settings

### PR DESCRIPTION
**Pull request by thewebartisan7**
Possible fix for issue https://github.com/anlutro/laravel-settings/pull/122

### CODE REVIEW

**Comment by bweston92** [comment]
@thewebartisan7 do you have time to test it? Currently away from PHP at the minute.

**Comment by thewebartisan7** [comment]
I will try find time this week.

**Comment by thewebartisan7** [comment]
@bweston92 the problem is that test without any change failed.
There are 14 errors.
I tested using version 0.9.0 and Laravel 6.2

Should I setup something or it's enough `composer install && vendor/bin/phpunit` ?

This is errors:

```
$ vendor/bin/phpunit
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.

.EE.EEE.EE.EEE.E................................EEE.....E         57 / 57 (100%)

Time: 78 ms, Memory: 8.00MB

There were 15 errors:

1) DatabaseTest::written_changes_are_saved
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.defaults.foo"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:54
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:28
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:46

2) DatabaseTest::nested_keys_are_nested
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:54

3) DatabaseTest::can_forget_key
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:72

4) DatabaseTest::can_forget_nested_key
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:87

5) DatabaseTest::can_forget_all
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/DatabaseTest.php:36
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:122

6) JsonTest::written_changes_are_saved
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.defaults.foo"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:54
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:28
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:46

7) JsonTest::nested_keys_are_nested
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:54

8) JsonTest::can_forget_key
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:72

9) JsonTest::can_forget_nested_key
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:87

10) JsonTest::can_forget_all
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:21
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:125

11) MemoryTest::written_changes_are_saved
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.defaults.foo"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:54
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/MemoryTest.php:13
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/functional/AbstractFunctionalTest.php:46

12) DatabaseSettingStoreTest::correct_data_is_inserted_and_updated
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/unit/DatabaseSettingStoreTest.php:40

13) DatabaseSettingStoreTest::extra_columns_are_queried
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.defaults.foo"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:54
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/unit/DatabaseSettingStoreTest.php:58

14) DatabaseSettingStoreTest::extra_columns_are_inserted
Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method



/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:93
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:261
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/src/SettingStore.php:146
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/unit/DatabaseSettingStoreTest.php:78

15) JsonSettingStoreTest::throws_exception_when_file_contains_invalid_json
Mockery\Exception\InvalidCountException: Method get("fakepath") from Mockery_4_Illuminate_Filesystem_Filesystem should be called
 exactly 1 times but called 0 times.

/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/CountValidator/Exact.php:37
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/Expectation.php:306
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/ExpectationDirector.php:120
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/Container.php:297
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery/Container.php:282
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/vendor/mockery/mockery/library/Mockery.php:162
/Users/mir/Projects/laratest/vendor/anlutro/l4-settings/tests/unit/JsonSettingStoreTest.php:9

ERRORS!
Tests: 57, Assertions: 58, Errors: 15.
```

**Comment by bweston92** [comment]
Can you rebase on master? Tests should also be fixed thanks to @aglipanci

**Pull request closed without merging**
