### PR TITLE
Adds timestamps

### PR DESCRIPTION
**Pull request by pratikkapasi**
Adds the 2 timestamps `created_at` and `updated_at` in the `settings` table

### CODE REVIEW

**Comment by anlutro** [comment]
Hello and sorry for not responding to this! I was very busy and then simply forgot.

I'm not sure if it's a good idea to include these columns by default, but I definitely think it should be possible with customization. I'd be willing to merge this if you

- make the column settings `null` by default
- don't set the columns if they are set to null
- remove from the default migration

I also like making `load` public with a `$force` argument, that's a great idea!

Are you OK with making these changes? If not I could try to continue your work when I have time.

**Comment by bweston92** [comment]
Hi @pratikkapasi any update on PR?

**Comment by pratikkapasi** [comment]
Hi @bweston92, sorry was offline for quite some time, so could not get back. I shall make the changes and update the PR soon.

**Comment by bweston92** [comment]
@pratikkapasi no need to be sorry :D take your time, just was wanting to know if it was dead or not.

**Comment by bweston92** [comment]
There is some conflicts with master which will need resolving too.

**Comment by bweston92** [comment]
Closing for inactivity, feel free to open again.

**Pull request closed without merging**
