### PR TITLE
Add Support for Laravel 6.0

### PR DESCRIPTION
**Pull request by backstageel**

### CODE REVIEW

**Comment by ilirhushi** [comment]
Hi @anlutro @backstageel ,

Any help with this, I am waiting for this PR to be merged since I can not upgrade to Laravel 6

Thanks.

**Comment by bweston92** [comment]
@ilirhushi there is a few issues with the migration they can be found here: https://github.com/anlutro/laravel-settings/issues/117#issuecomment-528245018

**Comment by bweston92** [comment]
@ilirhushi I have added a recommended fix for this, can you use `dev-master` and see if it is working as expected? If so I will tag a release.

**Comment by ilirhushi** [comment]
@bweston92  I will try with `dev-master` and I will let you know

Thanks

**Pull request merged**
