### PR TITLE
Change lists method to pluck - lists method is removed in Laravel 5.3

### PR DESCRIPTION
**Pull request by sangnguyenplus**
Hi @anlutro ,
Lists method is removed in Laravel 5.3 so please review and merge my pull request.
When it is merged, this package can work properly on Laravel 5.3.
Thanks.

### CODE REVIEW

**Comment by bweston92** [comment]
@anlutro I can confirm that this will work the docblock for `lists` in 5.3 said:

```
    /**
     * Alias for the "pluck" method.
     *
     * @param  string  $column
     * @param  string|null  $key
     * @return array
     *
     * @deprecated since version 5.2. Use the "pluck" method directly.
     */
    public function lists($column, $key = null)
```

https://github.com/laravel/framework/blob/5.2/src/Illuminate/Database/Query/Builder.php#L1856

**Comment by bweston92** [comment]
How-ever `pluck` doesn't have a different behaviour in Laravel 4 (I currently use Laravel 4) where it only plucks from the first result.

**Comment by anlutro** [comment]
So basically if we want full backwards compatibility, we have to do an `if (method_exists($query, 'lists'))` to determine whether to use `lists` or `pluck`?

**Comment by bweston92** [comment]
Provided a PR for him - sangnguyenplus/laravel-settings#1

Tests are for some reason failing.

**Comment by anlutro** [comment]
I pushed the fix myself. Thanks for letting me know about this!

**Pull request closed without merging**
