### PR TITLE
Remove laravel/helpers dependency

### PR DESCRIPTION
**Pull request by fsavina**
Use `Arr::dot` (already included in `laravel/support`) instead of `array_dot` and remove the `laravel/helpers` unnecessary dependency.

### CODE REVIEW

**Comment by anlutro** [comment]
I'm fine with this, but it seems like the `Arr::dot` method was added in 4.2, so we'll have to change our minimum version to that. Which is no problem as far as I'm concerned, I hope people updating are using more recent versions...

**Comment by anlutro** [comment]
Yeah I know :p If you change the version constraint to `>= 4.2` I'll merge this.

**Comment by fsavina** [comment]
There you go!

**Comment by anlutro** [comment]
Thanks! There'll be a new version tagged within the next couple of days.

**Pull request merged**
