### PR TITLE
Override configs and Blade directive

### PR DESCRIPTION
**Pull request by rubensrocha**
1. Override configs  and Blade directive imported from `akaunting/setting`
2. Added Laravel <= 5.7 and >= 5.8 compatibility
3. Avoids rewriting the json file when there is equal data

### CODE REVIEW

**Comment by bweston92** [comment]
Can you update the tests for JSON store to test the `Avoids rewriting the json file when there is equal data` feature.

**Comment by rubensrocha** [comment]
Sorry, I have no practice with testing at this time.

**Comment by bweston92** [comment]
Can you remove the check for this PR and create another PR with it for further discussion.

**Comment by rubensrocha** [comment]
I bought a Testing course at Udemy yesterday, but it will take a while for me to learn how it works and to be able to create a test for the modification I made.

However, I downloaded your package in a separate location and when I run the tests from the original version (I used git clone + composer install), the **JsonTest** and **JsonSettingStoreTest** tests already return errors.

**Using**
Laragon with PHP 7.2.11
Git Bash
Composer 1.9.0

JsonTest
---------
> 1) JsonTest::written_changes_are_saved
> Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.defaults.foo"). Either the method was unexpected or its arguments matched no expected argument list for this method
> 
> 2) JsonTest::nested_keys_are_nested
> Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method
> 
> 3) JsonTest::can_forget_key
> Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method
> 
> 4) JsonTest::can_forget_nested_key
> Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method
> 
> 5) JsonTest::can_forget_all
> Mockery\Exception\NoMatchingExpectationException: No matching handler found for Mockery_0::get("settings.forgetCacheByWrite"). Either the method was unexpected or its arguments matched no expected argument list for this method

JsonSettingStoreTest
-----------------------
> 1) JsonSettingStoreTest::throws_exception_when_file_contains_invalid_json
> Mockery\Exception\InvalidCountException: Method get("fakepath") from Mockery_0_Illuminate_Filesystem_Filesystem should be called
>  exactly 1 times but called 0 times.

**Comment by bweston92** [comment]
Can you rebase on master? This should also fix the tests thanks to @aglipanci

**Pull request closed without merging**
