### PR TITLE
Added save middleware

### PR DESCRIPTION
**Pull request by garygreen**

### CODE REVIEW

**Comment by anlutro** [comment]
Do other packages do the `pushMiddleware` thing? I think I'd prefer it if it was left up to the user to insert the middleware - that'll make it possible for them to alter the order of middlewares freely.

**Comment by garygreen** [comment]
To be perfectly honest i'm puzzled by that too. I think best practise would be to add it to the readme as part of the installation instructions to add the middleware in your application (if you want it to auto-save etc), but not much information around that subject for L5...

**Comment by anlutro** [comment]
I think the readme etc. route is the way to go. Some may want to disable the middleware entirely for performance reasons or just to keep it simple.

Do you want to reset the service provider and amend/rebase the commit or should I just merge and fix it later?

**Comment by garygreen** [comment]
Yup, I'll rebase and update the readme too.

**Comment by garygreen** [comment]
@anlutro All update to date now. How's it look to you? :-)

**Comment by anlutro** [comment]
Awesome. Thanks!

**Pull request merged**
