### PR TITLE
Allow seralizing options to be past to json store.

### LINKED ISSUE #44: Json pretty print
add pls JSON_PRETTY_PRINT for JsonSettingStore:write(). This will be very helpfull, i gues :)

### PR DESCRIPTION
**Pull request by bweston92**
Closes #44

NOT TESTED, DONE IN GITHUB EDITOR. DO PROOF READ.

### CODE REVIEW

**Comment by anlutro** [comment]
Github editor is nothing to scoff at! Should have at least a couple of tests though, especially because bitwise operations are so foreign to people like me.

**Comment by bweston92** [comment]
Will do give me 24 hours :p

**Comment by bweston92** [comment]
Tests added.

**Comment by bweston92** [comment]
You're still supporting PHP 5.3 really?

**Comment by anlutro** [comment]
I'm not really putting any effort into this package so saying I "support" 5.3 may be a stretch... but yes, that's what it was originally set up for.

**Comment by bweston92** [comment]
Closing due to inactivity.

**Pull request closed without merging**
